/* Generated By:JavaCC: Do not edit this line. CSAWQueryGrammarConstants.java */
package iitb.CSAW.Query.Parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CSAWQueryGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPR = 4;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int COMMA = 7;
  /** RegularExpression Id. */
  int QUOTE = 8;
  /** RegularExpression Id. */
  int UNDERSCORE = 9;
  /** RegularExpression Id. */
  int ENTBEG = 10;
  /** RegularExpression Id. */
  int ENTEND = 11;
  /** RegularExpression Id. */
  int TYPBEG = 12;
  /** RegularExpression Id. */
  int TYPEND = 13;
  /** RegularExpression Id. */
  int CONBEG = 14;
  /** RegularExpression Id. */
  int CONEND = 15;
  /** RegularExpression Id. */
  int OW = 16;
  /** RegularExpression Id. */
  int UW = 17;
  /** RegularExpression Id. */
  int CONSTANT = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int ALPHABET = 20;
  /** RegularExpression Id. */
  int CAPSALPHABET = 21;
  /** RegularExpression Id. */
  int WORD = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<OPR>",
    "\"+\"",
    "\"-\"",
    "\",\"",
    "\"\\\"\"",
    "\"_\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"ow\"",
    "\"uw\"",
    "<CONSTANT>",
    "<DIGIT>",
    "<ALPHABET>",
    "<CAPSALPHABET>",
    "<WORD>",
    "\"\\n\"",
  };

}
